### ISSUE TITLE
no cygwin-rsyncd-3.2.3.0_installer.exe file in repository

### ISSUE THREAD

**Issue by matswat** [backuppc/cygwin-rsyncd#7]
Please add this file to repo - it will make life easier for many users.

**Comment by craigbarratt** [comment]
I'll include it with the released files when I do the next release.

However, because of [this issue with rsync 3.2.3](https://github.com/WayneD/rsync/issues/95), it won't work on BackupPC 3.x unless `File::RsyncP` is at least [version 0.76](https://metacpan.org/pod/File::RsyncP).  So I'm wondering whether it's sufficient to include that warning in the release notes, or instead modifying the included rsync so it doesn't break BackupPC 3.x with versions of `File::RsyncP` prior to 0.76.

**Comment by docfactory37** [comment]
But would it work with backuppc 4.x ?

**Comment by craigbarratt** [comment]
Yes - 4.x will work fine.  This is just an issue that affects BackupPC 3.x.

I have built a version that makes `--no-msgs2stderr` the default, and that's the version I plan to release (soon).

**Comment by craigbarratt** [comment]
I released 3.2.3.1, so the installer is now available.
